schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "molecularnodes"
version = "4.2.0"
name = "Molecular Nodes"
tagline = "A toolbox for molecular import and animation in Blender"
maintainer = "Brady Johnston<brady.johnston@me.com>"
type = "add-on"
website = "https://bradyajohnston.github.io/MolecularNodes"
platforms = [
	"macos-arm64",
]
tags = [
	"Geometry Nodes",
	"Import-Export"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:MIT"
]
copyright =[
	"2022-2024 Brady Johnston",
]


wheels = []
platform = "macosx_10_9_x86_64"

[permissions]
network = "Downloading structural data from the PDB and AFPDB"
files = "Importing data files from disk and caching downloads"
