schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "molecularnodes"
version = "4.2.0-macosx_12_0_arm64"
name = "Molecular Nodes"
tagline = "A toolbox for molecular import and animation in Blender"
maintainer = "Brady Johnston<brady.johnston@me.com>"
type = "add-on"
website = "https://bradyajohnston.github.io/MolecularNodes"
tags = [
	"Geometry Nodes",
	"Import-Export"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:MIT"
]
copyright =[
	"2022-2024 Brady Johnston",
]


wheels = [
	"./wheels/pandas-2.2.2-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/fonttools-4.53.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/fasteners-0.19-py3-none-any.whl",
	"./wheels/urllib3-2.2.1-py3-none-any.whl",
	"./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
	"./wheels/MDAnalysis-2.6.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/starfile-0.5.6-py3-none-any.whl",
	"./wheels/joblib-1.4.2-py3-none-any.whl",
	"./wheels/scipy-1.13.1-cp311-cp311-macosx_12_0_arm64.whl",
	"./wheels/numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/certifi-2024.6.2-py3-none-any.whl",
	"./wheels/tqdm-4.66.4-py3-none-any.whl",
	"./wheels/kiwisolver-1.4.5-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/biotite-0.40.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/pytz-2024.1-py2.py3-none-any.whl",
	"./wheels/pyparsing-3.1.2-py3-none-any.whl",
	"./wheels/msgpack-1.0.8-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/requests-2.32.3-py3-none-any.whl",
	"./wheels/mmtf_python-1.1.3-py2.py3-none-any.whl",
	"./wheels/threadpoolctl-3.5.0-py3-none-any.whl",
	"./wheels/cycler-0.12.1-py3-none-any.whl",
	"./wheels/GridDataFormats-1.0.2-py3-none-any.whl",
	"./wheels/pyarrow-16.1.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/tzdata-2024.1-py2.py3-none-any.whl",
	"./wheels/biopython-1.83-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/idna-3.7-py3-none-any.whl",
	"./wheels/six-1.16.0-py2.py3-none-any.whl",
	"./wheels/packaging-24.1-py3-none-any.whl",
	"./wheels/mrcfile-1.4.3-py2.py3-none-any.whl",
	"./wheels/typing_extensions-4.12.2-py3-none-any.whl",
	"./wheels/networkx-3.3-py3-none-any.whl",
	"./wheels/matplotlib-3.9.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/contourpy-1.2.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/pillow-10.3.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl",
]

[permissions]
network = "Downloading structural data from the PDB and AFPDB"
files = "Importing data files from disk and caching downloads"
