project:
  type: website
  output-dir: .
  render:
    - '*.qmd'
    - '*.md'
website:
  title: "Molecular Nodes"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.md
        text: Home
      - installation.md
      - getting-started.md
      - examples.md
      - documentation.md
      - section: Python API
        contents: reference/*
    tools:
      - icon: github
        href: https://github.com/BradyAJohnston/MolecularNodes
      - icon: twitter
        href: https://twitter.com/bradyajohnston
      - icon: youtube
        href: https://youtube.com/c/bradyjohnston
  page-footer:
    left: "This site is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#F8F9FA"

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2


# quartodoc -------------------------------------------------------------------

quartodoc:
  package: null

  # NOTE: here's the source_dir argument! ----
  # it is expanded relative to _quarto.yml, but you can also
  # use a relative path: /path/to/src
  source_dir: ../MolecularNodes
  sections:
    - title: Python API
      desc: The Python code that powers Molecular Nodes under the hood.
      contents:
        - name: pkg
          children: flat
        - name: load
          children: flat
        - name: nodes
          children: flat
        - name: coll
          children: flat


